
services:
  postgres:
    image: postgres:15
    container_name: postgres_db_productos
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: products_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  api:
    build: ./backend_productos
    container_name: api_backend_productos
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
    - ./backend_productos/.env.docker
    ports:
      - "3001:3001"
    volumes:
      - ./backend_productos:/app
      - /app/node_modules
    command: ["sh", "-c", "npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all && npx nodemon src/index.ts"]

  frontend:
    build: ./frontend_productos
    container_name: frontend_productos
    restart: always
    env_file:
      - ./frontend_productos/.env.docker
    depends_on:
      - api
    ports:
      - "80:80"

volumes:
  postgres_data:
