# version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db_productos
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: products_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  api:
    build: .
    container_name: api_backend_productos
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: products_db
      DB_PORT: 5432
      PORT: 3002
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["sh", "-c", "npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all && npx nodemon src/index.ts"]

volumes:
  postgres_data:
